services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENV: docker
      DOCKER_MONGO_URI: mongodb://mongo:27017/mydb
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"